name: auth

services:
  auth-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env # rendered by master CI/CD on VM
    environment:
      PORT: 8001
      APP_ENV: production
    ports: ["8001:8001"]
    restart: unless-stopped
    networks: [app_network]
    container_name: auth-api
    mem_limit: "512m"
    cpus: "0.5"

networks:
  app_network:
    external: true
    name: app_network
