name: advensis_auth_service

services:
  tenant-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      PORT: 8001
      DB_HOST: advensis_postgres
      APP_ENV: production
      ENVIRONMENT: production
    ports: ["8001:8001"]
    command: ["/app/entrypoint.sh"]
    restart: unless-stopped
    networks: [app_network]
    container_name: tenant-api
    mem_limit: "512m"
    cpus: "0.5"

networks:
  app_network:
    external: true
    name: app_network
