name: advensis-service-prod

services:
  advensis-service-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env # rendered by CI/CD on VM
    environment:
      PORT: 8090
      APP_ENV: production
    ports: ["8090:8090"]
    restart: unless-stopped
    networks: [app_network]
    container_name: advensis-service-api
    mem_limit: "512m"
    cpus: "0.5"

networks:
  app_network:
    external: true
    name: app_network
