name: advensis-service-dev

services:
  advensis-service-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.development
    environment:
      PORT: 8090
      APP_ENV: development
    ports: ["8090:8090"]
    restart: unless-stopped
    networks: [app_network]
    volumes:
      - .:/app
    container_name: advensis-service-api-dev
networks:
  app_network:
    external: true
    name: app_network
