name: advensis_tenant_service_dev

services:
  #  for local developement create a database
  postgres-dev:
    image: postgres:15
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: tenant_db_dev
    ports: ["5433:5432"]
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    container_name: postgres-dev
  tenant-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.development
    environment:
      PORT: 8001
      APP_ENV: development
      ENVIRONMENT: development
      DB_HOST: host.docker.internal
      DB_PORT: 5433
    ports: ["8001:8001"]
    restart: unless-stopped
    networks: [app_dev_network]
    volumes:
      - .:/app
    container_name: tenant-api
networks:
  app_dev_network:
    external: true
    name: app_dev_network
