name: advensis-service-stage

services:
  advensis-service-api:
    build:
      context: .
      dockerfile: Dockerfile.stage
    env_file: ./.env # rendered by CI/CD on VM
    environment:
      PORT: 8091
      APP_ENV: staging
      ENVIRONMENT: staging
    ports: ["8091:8091"]
    command: ["/app/entrypoint-stage.sh"]
    restart: unless-stopped
    networks: [app_stage_network]
    container_name: advensis-service-api-stage
    mem_limit: "512m"
    cpus: "0.5"

networks:
  app_stage_network:
    external: true
    name: app_stage_network
