name: auth-dev

services:
  auth-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.development
    environment:
      PORT: 8001
      APP_ENV: development
    ports: ["8001:8001"]
    restart: unless-stopped
    networks: [app_network]
    volumes:
      - .:/app
    container_name: auth-api
networks:
  app_network:
    external: true
    name: app_network
