name: advensis_tenant_service_stage

services:
  tenant-api-stage:
    build:
      context: .
      dockerfile: Dockerfile.stage
    env_file: ./.env
    environment:
      PORT: 8051
      DB_HOST: advensis_postgres_stage
      APP_ENV: staging
      ENVIRONMENT: staging
    ports: ["8051:8051"]
    command: ["/app/entrypoint.sh"]
    restart: unless-stopped
    networks: [app_stage_network]
    container_name: tenant-api-stage
    mem_limit: "512m"
    cpus: "0.5"

networks:
  app_stage_network:
    external: true
    name: app_stage_network
